var employeesData = {
    "LAZ": ["Susmono", "Syamsiyati", "Rahmad Arif Setiawan", "Pudagiwa", "Tia Nuryani", "Izza Hanifa Urfa", "Muhammad Ridho", "Fina Maratus Sholihah", "Anggi Prasetyo", "Galang Ma'ruf", "Taufik", "Dwi Hartanto", "Totok Supriyanto", "Budi Setyo", "Nindy", "Tri Suryani", "Wiby", "Upik Yusmianti", "Hanny", "Siti Solikhatun", "Bilqis", "Suparningsih", "Siti Zulaikhah", "Cristiawan HN", "Dian Ardianto Setyo S", "Ravenna Dewi Andriana", "Dwi Ayu Novita Aryani", "Mecky D H", "Tamamun Nadlirin", "Ridwan Setiawan", "Siti Fatimah", "Septi", "Sri Rahmawati", "Ariska"],
    "Boarding": ["Aidah Mubatillah Al Khumsaa", "Alifuddin Yusuf Adisuseno", "Ardia Veriana Saputri", "BU MULYANI", "Fatimah", "Galang Ma'ruf", "Giant Ramadhan Syah", "Hasbina Khoiriyah", "Hidayah Zulirakani, S.Pd.", "Imam Aji Cahyono", "Khoirul Arsyad Abdullah", "Lu'lu' Rosyidah Rofifah", "Luthfiyah Miftahur Ramdhani", "M Hanif Aditya", "Mahmud Al Ghoziri", "Miftahul Arkhan", "Muh. Bisri Mustofa", "Muhammad Syafiq", "Muhammad Syihabuddin Annur,S.Pd.", "MUHAMMAD ABDULLAH FAUZAN", "Mutiara Nurani Suci S.Pd", "Qonita", "Siti Sholikhatun", "Zahrotul Khasanah", "Ziat Rahman Hakim", "Firda Azaria", "Luthfia Shifaul Amanah Burhani ", "Aidah ", "Ammar Zain Marzuqi", "Balqis Sakhaa Ilafi", "Melinda Retno Diningrum", "Itsna Rachmawati Dewi"],
    "SDICT Surakarta": ["Alfi Mubayyinah, S.Pd", "Amalia Khusnu, S.Pd", "Ana Nur Chasanah, Ssi.", "Ana Sholekah Aszar", "Apriyani Indri Trisnawati, S.Pd", "Ari Sugiyono, S. Pd. I., S.Pd.", "Ayu Oktavia Rosanti, S. Pd.", "Choirul Anwar, S. Pd", "Deri Rahmania Luhri, S.Pd", "Dhian Fitriana, S.Pd.", "Diana Putri Hidayati", "Dimas Tegar Mahardhika, S.Pd", "Dwi Kresna Yulianti, S.Pd", "Eko Setia Watiningsih, S.S.", "Elva Herlin Yeliana, S.Pd", "Endah Aprilia Purwaningrum.M.Pd.", "Erinda Sari Dwi Astuti, S.Pd", "Fadiah Azmi Rahmasari, S.Pd.", "Fadlilah Ramadhani, S.Kom.", "Hafida Aminindia, S.Pd", "Heldayani", "Hendri", "Kanti Wismanjari, S.Sos., S.Pd.", "Mochamad Syamsudin Alpalanju, S.Pd", "Mochammad Jauhari Achmad, S.Pd", "Mukhsin, S.Pd", "Nadia Novemi Putri", "Nanik Yulianti,S.P", "Putri Salwa Salsabila, S.Pd", "Rahmawati Eki Pujiastuti, S.Pd", "Regita Asharani, S.T", "Riski Mukaromah, S.Pd", "Rosita Pamulia Andani,S.S.", "Taufiq Ma`ruf", "Tri Wijayanti,S.Pd.M.Pd.", "Qhoirul Annisa Firdaus, S.Si", "Megarani Desianingtyas, S.Si"],
    "SDII Boyolali": ["Agustin Fatikasari", "Athifatun Najiyah, S.Pd", "Bilkhis Sri Maharani, S.Pd", "Catur Romadloni Pujarwati, S.Pd", "Fadlan Rifai Al-Irsyad", "Faradila Ardana, S.Pd", "Gita Sidiq Kurniawati, S.Pd", "Hanifa Amri Fatonah", "Iin Nur Chasanah,S.Pd.", "Inayah Al Fatihah, S.Pd", "Intan Jannah Dikhawati, S.Pd", "Joko Santoso, A.Md", "Kuntadi, S.Pd", "Lia Vibrianti, S.Hum", "Maesaroh, S.E", "Maryanto", "Maulidiya, S.Ag", "Melinda Nur Cahyaningrum, A.Md.Kep", "Muhammad Amirudin Arrofi'I, S.Pd", "Muhammad Nurokhim Nawawi, S.Pd", "Nella Putri Rahmawati, S.Pd", "Nur Fatimah, S.Pd", "Nur Halim", "Rizki Fajar Ramdani,S.H.", "Rizqi Ashrifah Qurotaayun, S.S", "Sidik Rohmanto, S.Kom", "Sunardi", "Syafi'ul Umam, S.T", "Syifa Kusuma Wardani", "Tsabita Faiz Ihsani", "Umahatul Kibriya, S.Pd", "Umi Robbayani, S.Pd", "Yasmina Bilqis Muharromah", "Yuli Hari Murti, S.Pd.", "I Gusti Viana Anggita Zunaini, S.Pd", "Muhammad Furqon Al-Fariqi, S.Pd", "Dwi Safitri, S.Pd"],
    "SDII Karanganyar": ["Ammetyas Kunthi Rachmadhini, S.Pd", "Arif Munandar, S.Ag.", "Ismi Wakhidah", "Medhika Alvania Pebriyani, S.Pd", "Riyani Halal Hanifah, S.Pd", "Suparman", "Tri Wulandari,S.Pd.", "Yeniar Elka Pramesiana, S.Pd"],
    "SDII Klaten": ["Choirul Anwar Al, SPd.", "Ekawati Yunitasari Putri A.Md.", "Vela Maria Ulvah,S.Pd.", "Wiharastro Anan Pudyantoro,S.T, S.Pd.", "Lulu Fikti Anisah, S.T", "Fatimah Az Zhara, S.Si"],
    "SDII Sragen": ["Anton Munadi, S.Pd.", "Eka Nydia Ayu,S.Pd.", "Maimunah, S.Pd.", "Matsna Sabila Malik, S.H", "Murniyati, S.Kom", "Nonik Nataliya,S.P.", "Nur Aisyah, M.Pd.", "Rahma Putri Utami, S.P", "Riana Evi Nurita, S.Pd.", "Salma Nur Nafisah, S.Pd", "Sunarto, S.T, S.Pd.", "Umi Nur Khasanah, M.Pd.I", "Wahyu Adhi Nugroho,M.Pd.", "Galih Satria", "Shedy Amalia Rozzaqi ", "Ellya Saljadziba, S.Pd.", "Itsla Kamila Nasikh"],
    "SDII Sukoharjo": ["Abdullah Akram", "Abdullah Hasan A", "Agus Nugroho, S.T., S.Pd", "Choiriyah,S.Pd.", "Dinda Rendrasetya Hilmy", "Fajar Desia Cahyani, S.Pd.I", "Putra Darmawan, S. S", "Putri Apriliana", "Weni Aprilia Pradani, S.Pd", "Yuli Purwantiningsih", "Valensa Ihsa Mahendra", "Islamiah Pratiwi Ayu Larasati, S.Pd", "Arini Diana Sari"],
    "SDII Surakarta": ["Ade Rachmad Said", "Amin Mustofa,S.Hum.", "Anggi Firmasari, S.Pd", "Anita Maharani Kasnara, SS", "Annisa Lina Syarifah,S.Pd", "Arif Mashudi, ST", "Arwan Joko Supriyono, S.Pd.I", "Aulia Firdausia Putri,S,Pd", "Azimatul Afifah,S.H.", "Chamimah Ahsaniyati,A.Mk", "Dessya Diah Rahmawati, S.Pd", "Dika Ananda, S.Pd", "Efa Wahyuni, S.I.Kom", "Eri Munandar", "Fadlilah Din Rohimin, S.Pd", "Fatima Azzahra, S.Pd.I.", "Fatimah Azizah,S.KM.", "Fawwaz Dhiyaaul Haq, S.Pd.", "Fitria Yulianti S.Sos.", "Hazna Wahyuningsih,S.Pd.", "Imaniar Dyah Rahmawati, S.Pd", "Kudratullah, S.S.", "Lia Adhedia, SS", "Lisna Rahmawati", "Listyowati,S.Pd", "Lukman Nul Hakim, S.Pd.", "Lutfi Istiqomah, S.T, S.Pd", "M. Adi Ramelan", "Mais Al Mubarok Fi Daroini,S.Pd.", "Malik Argo Santoso, S.Pd, M.Or", "Mashuri, S. PdI", "Mohammad Thoriq,S.Pd.", "Muflichatun Nisa`,S.S.", "Muhammad Mustaghfir Al-Anshori, S.Pd", "Ninik Suparyanti, S.Sos", "Nur Azizah, S.S", "Nur Rohmah Hidayanti", "Nurfita Widyastuti,S.Pd.", "Nurul Fadhilah, S.Pd", "Pinky Tri Anggilia,A.Md", "Putri Eko Novita Sary,S.Pd", "Ria Intan Prasetyo,S.Pd", "Sholimin", "Siti Romelah, S.Pd", "Sri Wachyuningsih,S.Pd.,Gr.", "Suparno,S.T", "Tim Komputer", "Titis Dyah Ekowati, S.Pd", "Tukiyo ", "Uswahtun Hassanah,S.Pd.", "Uswatun Khasanah, S.Pd", "Wahyu Sari Mukti, S.Pd", "Yosi Anggraeni Wisnu Kusumaningtyas, S.Pd", "Yuni Siswanti, S.Pd", "Zaini Muharom, S. S., S.Pd.", "Zeni Vera Wati, S.Pd", "Mufti Khoirunnisa', S.Pd"],
    "SDII Yogyakarta": ["Ajeng Aprilia Husaeni, S.Pd", "Kartika Desy Purwanti,S.Pd.", "Muhammad Naufal Ilyas Saputra"],
    "SDTQ Surakarta": ["Abbad Said Muhammad,S.Pd", "Abu Dawud Kasruri", "Agung Wahyu Utomo, S.Pd", "Anis Setyowati, S.Pd", "Annur Indah Sari, S.Pd.I", "Arif Budiyono.S.Pd.I.", "Arista Kunti Habsari, S.Pd", "Artanti Wulansuci Utami, S.Pd", "Ayu Sholichah, S.S", "Azizah Al-Ayyubi", "Devie Ayu Arinikha,S.PdI", "Dewi Mifta Maya Andira, S.Pd", "Dizki Aji Pangestu, S.Pd", "Dyah Astari, S.T.", "Elya Retna Purwaningtyas, S.T", "Ernawati, S.Sos.", "Fathullah, SE. Sy", "Fatnia Ulul Arfiyanti,S.Pd.", "Hastinnailul Mawadah, S.Kep", "Indah Kurniawati, S.S., S.Pd", "Indriyani, S.Pd", "Khoirun Nisa,S.PdI", "Kuswardani Dyah Ayu Kusumaningrum, S.Ag", "Luth Hafizh Bahtiar, S.Pd", "Lutviyana Galih Paswatiningsih,S.H.", "Masrukan,S,Pd.", "Melani Ismoyowati, S.Pd", "Muhammad amin", "Muhammad Faisal Alaq Qodrian Efenfdi", "Muhammad Mushab", "Munawaroh,S.Pd.I", "Nafi Umi Atmaja, S.Pd", "Nanik Sulistiyo Rahayu", "Nur Anisa", "Nurul Humaeroh Kartiko Winar, S.Pd", "Nur`aini, SPd.", "Paramadina Santri", "Rin Fibriana, S.Psi.,S.Pd.I", "Rizal Mustofa", "Rohmat Roi Waldi, S.Pd", "Siti Chotijah, S.Pd.", "Siti Nurhayati, S.Pi", "Siti Rofiyatun,S.Pd", "Sri Utami, S.Pd.I.", "Sumiyati,S.Hum.", "Wahyu Catur Rini", "Warti, S. Si.", "Zhahrul Makhfud, S.Pd", "Dina Arifatul Khusna", "Maia Ameilyana Zapin ", "Ummu Izzatul Uswatun khalisah ", "Ari Rahmawati ", "Ahmad Fahmi Alfian", "Deka Selfiana"],
    "SMA ABBS": ["Abd Azis, S.Pd.I.", "Abdulloh Al Haris Dzulfikri,S.Pd", "Achrudin, S.Pd., Gr.", "Adilah Hasna,S.Pd.", "Agung Sularso, S.Pd,Gr.", "Ahmad Subandi", "Alfi Suryani Yusuf,S.Pd", "Amira Muflicha Daraini, M.Pd.", "Amirul Setiawan,S.Pd.", "Anggi Puspa Wijayanti Wiaz, S.Sos", "Anna Rafaidah, S.Pd.", "Aripiyanto", "Asnia Novitasari. AM, M.E", "Asy Syifa Labibah,S.Pd., M.Sc", "Aulia Nur Ridwan, S.Pd., Gr.", "Azhar Umam, S.Pd", "Dhiyas Fatin Nuha,S.Pd.", "Dwi Noviasih Pratama,S.Pd", "Fadhilah Kusumasari, S.Pd", "Fandi Agus Irawan, S.Pd", "Fatimah Azzahroh, S.Pd", "Fatimah Zahro Assidiqoh, S.Pd", "Febrianto Agus Wirasto,A.Md.", "Fitri Nur Hardiyani, S.Pd.I", "Frenika Widyasari, M.Pd", "Hana Agustyaningrum, M.Pd.", "Hasna Alfasina,S.Pd", "Hesti Indah Mifta Nur'aini, S.Pd, M.Pd", "Ina Yuliyati,S.Pd.", "Inna Rizki Apriyanti, M.Pd., Gr.", "Intan Widya Pangestika, S.Pd, M.Si", "Isnaini Umi Nurhasanah,M.Pd", "Isykarima Amalia Vita Noor Izzaty, S.Pd", "M. Thoriq Hanafi, S.Pd", "Marwanto", "Mochamad Hafid Rozaqi", "Muhammad Abdul Azis, S.Pd.", "Muhammad Zaenuddin, S.E.I", "Naimina Restu An Nabil, S.Pd.", "Nasyalina Dwinta, S.Pd", "Nina Setyowati, S.Pd", "Novilia Nugraheni, M.Pd", "Nur Masitoh,S.Pd.", "Nur Shofa Riyana, S.Si", "Nurul Fadhila Firdaus, S.Pd", "Ocnatias Eka Saputri, S.Kep, M.Psi", "Putera Islamiyadi Rahmatullah,S.Kom.", "Putri Oktaviani, S.Pd", "Qothrun Nada Husna", "Rahma Nur Afifah, S.Pd", "Rajini,S.Pd,M.Pd", "Ratih Tri Wijayanti, S.Pd", "RENGGA NGESTHI PAMBUKA, S.PD", "Rini Kurniasih, M.Pd", "Salmaa Khoirun Nisaa', S.Kom", "Sari Melati Kusuma Astuti, S.Pd.", "Sela Mawarti, M.Pd.", "Shofwa Annisaa, S.Pd.", "Siska Wahyuningtyas Retno Wulandari, S.Pd.", "Solikatun, S.Pd", "Sri Mulyani, S.Pd", "Supriyono", "Sutarto", "Syih Almayanti", "Teguh Umarudin,S.Pd", "Titik Purwanti,S.Si.", "Tyas Wisnuwardani, S.Pd", "Umi Wahidatul Latifah, S.Pd.", "Uswatun Hasanah,S.Pd", "Virliana Annida Rekkayushar, S.Kom", "Wiji Setyo Utami, S.Pd", "Yunita Sari, A.Md", "Zahrotun Hanifah, M.Pd", "Zuly Irawan, S.Kom.", "Jonanda Fattah Anugerah, S.Pd. ", "Rikha Putri Devianti"],
    "SMP ABBS": ["Alla' Junia Nurdin, S.Pd", "Andi Wijayanto", "Eka Noer Maya Sari, S.T", "Fatma Roudhotul Rafida Kolis, S.Pd., Gr.", "Hari Rohmah, S.Pd", "Ida Aryani, S.  Sos.", "Iin Indah Saputri,S.Pd.", "Joko Ariyanto,S.T.", "Lutfa Usaidah", "Muamar Fariq Salafy, S.Pd, Gr.", "Muhammad Fahmi Aziz, S.Psi", "Rifqi Syarifudin", "Sharih Shadri,S.S.", "Sinta Fitriana, S. Pd", "Siti Asiyah Wardatul Jannah, S.Pd", "Siti Khoimah, S. Pd.", "Arvino Nurvieri Kusuma", "Scundy Nourma Pratiwi, M.Pd."],
    "SMPII Boyolali": ["Ami Nitami, S.Pd", "Dwi Indah Royani,S.Pd.", "Essy Dian Pratiwi, M.Pd", "Farrasa Uswatun Hasanah, B.A", "Fathimah Al-Zuhri,S.Pd", "Habib Hasan", "Lydia Carolin, BA", "Mohamad Arif Maulana,S.Pd.", "Muhammad Rois Adzkia, S.I.P", "Naili Mawadda, S.Si", "Phaksi Arwendha, M.Sn", "Purnamawati, S.Pd", "Rina Irawati, S.Pd", "Zeni Prasetyo", "Mutiara Nurani Suci", "Tungga Pramudya Utama", "Tia Izzah Fathiya", "Dani Dwi Susanti", "Balqis Sakhaa Illafi", "Fadlan Rifai Al Irsyad", "Winarso"],
    "SMPII Karanganyar": ["Arif Hidayat, S. Pd", "Darsono, S.Pd.", "Fhitri Indah Sari, S.Pd", "Indra Tri Ariyadi Suseno,S.Pd.", "Khusnul Karimah, S.Pd", "Mulyadi", "Nursita Yuliana", "Nurul Rizqa", "Nurul Rizqa b", "Retno Kusuma Astuti, S.Pd"],
    "SMPII Klaten": ["Ana Susanti, S. Pd", "Retno Wiyanti, S.Pd", "Muhammad Fachrudin Alwi, S.S"],
    "SMPII Sukoharjo": ["alqaan maqbullah ilmi, S.Pd., M.Pd., M.Si.", "Farida Leni Kusumawati, S.Pd", "Amatullah Ashshobriatu Nuha, S.Pd", "Anas Tas Nia Dewi Nur Komaria, S.Pd", "Anggita Widya Nugroho, S.Pd.", "Annisa Dwi Nursanti, S.Pd", "Ibrohim Abdul Alfatahu", "Mochammad Rizkia Putra", "Mukhlis Kurnia Aji, S.T", "Nur Afifah, S.Kom", "Putri Nurika Anggraini, M.Pd", "Shalindri Saraswati, S.Pd", "Yuzka Faiz Ad dzakie", "Luthfiyah Miftahur Ramdhani", "Septia Kiki"],
    "SMPII Surakarta": ["Adi Cahyo Nugroho", "Adi Irma Suryadi, S.Pd, M.Pd", "Adila Rahmah, S.Pd, M.Pd.", "Ahmad Bayu Abdulloh", "Ahmad Fauzi", "AHMAD SYAIFUL", "Aji Kusuma Negara", "Alfia Setya Rahmadevi, S.Pd", "Arlina Yuliastanti,S.Pd.", "Auriga Maulana Khasan, M.Pd", "Banna Handiyanto,S.Pd.I", "Danang Dwi Pambudi S. Pd", "Dewi Nur'aini", "Dewi Wijayanti,S.Kom", "Ekawati,S.Pd.", "Farras Astri Firyadani, S.Pd", "Fitri Nur Kholifah,S.Pd", "Fitria Rachmawati Zain,S.Pd.", "Hafiz Kurniawan, S.Pd", "Hannah Ummu Atikah, S.Ag", "Hari Prasetyo, A.Md.", "Heni Susilowati, S. Pd", "Idhan Khalik", "Ikhwan Caesar Amri Pradana, S.Pd", "Isti Qomah Nurul Izzati, S.Pd", "Joan Nofila Nurlinita,S.Pd.", "Khairun, S.Ag", "Kristantono,S.Pd.I", "Kurniawan Ridho Saputro,S.Pd", "Laili Khairun Nisa', S.Pd", "Lia Nuryani", "Luqfi Nurul Setiawan, S.Pd", "Mia Febriana,M.Pd.", "Mohamad Darril Hermawan, S.Pd.", "Muhammad Sultan Izzudin", "MUSFIQ AMRULLOH, S.Pd.", "Nafakah Aria Perkasa, S.Pd, M.Pd", "Nisa Ul Haq", "Nor Azizah, S.Sos", "Nurul Hidayah Kobir, S.Pd", "Nurul Hidayati,S.Pd", "Rina Wijayanti, S. Pd", "Rizal Mahfudin, S.Pd.", "Rizky Andriyanto, S.Pd", "Rois Patoni", "Saraswati,S.Si.", "Siti Zamronah Rizqiah", "Sri Wahyuni,S.Pd.", "Sriyanto,S.E", "Sutarto", "Titik Maryatun", "Trully Sanuri Damayanti, S.Si", "Ulfa Nurul Kurniawati", "Wela Ardha Permatasari, S.Pd", "Widhi Haryanto", "Yoki Wirawan, S.Pd", "Yudi Prasetiyo, S.Kom.", "Yustien Pramita Hapsari, S.Pd", "Zaenal Baharudin, A.Md", "Muh Bisri Mustofa "],
    "SMPII Yogyakarta": ["Mefta Rizki Qurrat 'Aini, S.Pd", "Muhammad Nadir", "Malisa Alifatul Izza Hapsari", "Nurul Khafidoh, S.S."],
    "SSU": ["Aji Wibowo", "Dwi Haryanto", "Yanuar Hafidh F"],
    "TKII Boyolali": ["Aida Dewi Astuti,S.Sos.", "Anisa Wafa Aulia,S.Pd.", "Annisa Amalia Rahmah, S.Pd", "Apri Ismulandari, S.Pd", "Arviana Dwi Suhartanti, S.kom", "Azizatul Itsna,S.Pd.", "Beltin Seftiana, S.Pd", "Dewi Rahmani", "Dinah Lestari, A.Md", "Fajar Hari Tamara, S.Pd", "Farida Nur Handayani, S.Pd.", "Hasna Atika Ningtyas", "Inannisa Izzatul Ni'mah,S.Pd.", "Intan Kumala Sari, S.Pd", "Kusnia Setiarti,S.Pd", "Nia Astutik, S.Pd", "Niken Popy Nur Laili Febriana, S.Pd.,Gr", "Nisaulmahmudah Nandipinta, S.Psi", "Nur Haqiqi, S.Pd", "Nurul Istiqomah, S.Pd", "Rufaida Umi Sholikhah,S.Pd.", "Rustia Wahyu Wijayanti, S.Pd", "Wahyu Arinta Rizki, S.Si", "Win Yunidar Setyawati, S.Pd", "Winda Wahyu Dianty, S.Pd, M.Pd", "Yuliana Sari, S.Pd", "Risma Khoirun Nisak, S. Pd"],
    "TKII Karanganyar": ["Amany Hidayah, S.Pd", "Fadhilah Nur Hidayah,S.S.", "Mikami Esta Anggraeni, S.Ak", "Pepsi Febriyanti, S.Pd", "Praditya Ayu Cahyani, S.Pd", "Rina Budhi Hidayah, S.Pd", "Tri Handayani, S.Pd", "Widya Ratnaningsih", "Wiwit Nur Aini, S.Pd", "Amaliya nur Azizah,S.Pd"],
    "TKII Klaten": ["Dewi Fathona Rahmawati", "Muhammad Alfitra, S.Pd", "Umi Sholichah, S.Pd", "Anisa Oktafia Fitriani, S.Pd."],
    "TKII Sukoharjo": ["Ahma Nur Aisyah, S.Pd", "Amalia Nisa Sholehah", "Andira Koza Laksita, S.Psi", "Annisa Fathaniah Anwar, S.Psi, S.Pd", "Aulia Umi Valentina, S.S", "Dinda Nadilla Sandy, S.Pd", "Fatimah Zakiyah, S.Kep.", "Ika Devi Pancasilawati, S.Pd", "Nilna Dati Layyina, S.S", "Nur Rohmawati, S.Pd", "Rosmalita Putri Isnaini, S.Pd", "Rusdi Ana Luthfi, S. S. I", "Siti Fatimah, S.H.","Yanu Toki Melliani, S.Pd.", "Dalal Hibatul Aisyi, S.Sn."],
    "TKII Surakarta": ["Alfinna Setya Rahayu", "Anisa Rosilawati Qurotul A'yun, S.Pd", "Desi Nurjayanti,S.Pd.", "Dessy Nuraini A., SS", "Dian Rifiah Irawati", "Dwi Erika Mufdiyati, SS", "Ervi Ari Listyani Wahono,S.Pd.", "Friska Arsalina, S.P.", "Imawati Rodhiyyana, S.Pd", "Ita Rusdiana, S. Pd", "Khoiri Hidayati", "Laela Nur 'Aini, S.Pd", "Laily Istifaiyah, S.Pd", "Malinda Hidayanti, S.Pd", "Marito Juli Yanti, S.Ag", "Mugi Rahayu,S.Pd.", "Nathasya Cindy Claudya", "Nina Nuroniah, S. Pd", "Nisa Hidayati", "Qonitatul Mahmudah, S.S", "Reny Apriyani, SE", "Siti Nur Khasanah,A.Mkg", "Siti Rochimah,S.Pd.", "Uswatun Hasanah, S.S", "Vylla Nurika Sari,S.Pd.", "Yuni Irawati, S.E.", "Yunita Miftakhunisa, S.Pd", "Sabiqoh Dwi Wahyuni", "Fauziah shoimah S.Pd", "Indah Sapta Ningrum"],
    "TKII Yogyakarta": ["Alyarahma Nur Aisya, S. T. P.", "Fidiana Nurhantari,S.Psi.", "Amrina Rosyada "],
    "TKQP Surakarta": ["Ardistha Yuliana Purbasari, S.Pd", "Dewi Ambarsari", "Dwi Toto Sarjono", "Farida Nur Aini,S.E.", "Ina Indrawati,S.Pd.", "Ira Desy Kusliniawati, S.Pd", "Latifatun Nisa,S.Pd.", "Nur Endah", "Putri Cahya Sari, S.Sn", "Ratih Listeriyadi, S.Si", "Rizky Faujiah, S.Kom", "Stefi Aulia Putri, S.Pd", "Tuwiyem, S. Pd", "Lina Dani Lestari, S.Pd"],
    "Yayasan": ["Ahmad Sulaeman, M.Pd", "Dian Octavianah,S.P.", "dr. Syayma Karimah", "Fahrizal Miftahuddin", "Farida Nur `Aini, S. Sos", "Fityatul Muharromah, S.P.", "Imam Samodra, S.Si., M.Si. Gr.", "Khanifudin, M.Pd.", "Khoiruddin, M.Sc.", "Muhammad Ridwanullah", "Muhammad Rizki Almalik", "Mulyani", "Nadya Nuryaningtyas", "Nur Islami Prayoganing Ayu, S.I.Kom", "Nurul Waridatil Zulfa,S.Pd.I", "Purno Budi AntoroS,Pd.I", "Sahlan Rasyid,S.SPd,I,S.Psi.", "Shodiqin, S.Pd", "Susanti,S.E.", "Triyadi, SPd.", "Muhammad Yusuf Fajri"],
    "PPTQ": ["Ust Muh Ihsan, S.Pd.", "Ust Fitri", "Ust Hasbina", "Usth Tursila", "Fitriya Az zahroh,S.Pd"],
    "STIAA": ["Ayu lestari", "Rino Saputro", "Desy", "Syifa", "Latifah", "Tsabita", "Annisa", "Alisha", "Miftah", "Zaenab", "Azizah", "Aini", "Hikmah", "Tety", "Fatimah", "Farah", "Umni", "Naya", "Galang", "Hanif", "Syaiful", "Ahmad"]
};

var unitSelect = document.getElementById("unit");
var employeeSelect = document.getElementById("employee");

// Populate employees based on selected unit
unitSelect.addEventListener("change", function() {
    var unit = unitSelect.value;
    employeeSelect.innerHTML = ""; // Clear existing options
    if (unit !== "") {
        employeesData[unit].forEach(function(employee) {
            var option = document.createElement("option");
            option.text = employee;
            option.value = employee;
            employeeSelect.appendChild(option);
        });
    }
});
